sudo: required
dist: trusty
language: node_js
node_js:
  - "7.8"
branches:
  only:
    - master
    - development
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run-script lint
  - npm run-script build
after_success:
  - "curl -u deploy:$DEPLOY_PASSWORD https://deploy.awix.io/deploy/frontend/$TRAVIS_BRANCH"
